### ISSUE TITLE
Image loading is broken

### ISSUE THREAD

**Issue by jmdoucette** [christian-doucette/owlbear-instant-summons#1]
<img width="1440" alt="Screen Shot 2024-02-20 at 8 42 04 PM" src="https://github.com/christian-doucette/owlbear-instant-summons/assets/62404099/205f93b2-84dd-4d9c-bcd7-199c21fdf87c">

It looks like all images were removed from 5e.tools ([example](https://5etools.tools/bestiary.html#aarakocra_mm)).

Probably the fastest fix would be switching to the 5e tools mirror on github ([example](https://5etools-mirror-2.github.io/bestiary.html#aarakocra_mm))

**Comment by christian-doucette** [comment]
Resolved
